set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CXX_FLAGS "/std:c++20")
set(VCPKG_C_FLAGS "")

list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS
    "-DHAVE_AF_INET6=1"
    "-DHAVE_INTTYPES_H=1"
)
